name: Update VRC-api

on:
  workflow_dispatch:
  schedule:
      # JST: 0 0 * * *  (UTC+9)
      # UTC: 0 15 * * *
    - cron: '50 14 * * *'

jobs:
  update-image:
    name: update images
    runs-on: ubuntu-latest
    steps:
      - name: mkdir
        run: mkdir -p public/api/v1/
      - name: date
        run: date > public/api/v1/commit
      - name: wget
        run: wget -T 10 'http://drive.google.com/uc?export=view&id=${{ secrets.API_ENDPOINT_VRC_CALENDAR }}' -O public/api/v1/vrc-calendar.png
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
          publish_branch: master
